### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by maxbeizer** [scrogson/phoenix-webpack-example#1]
@kevinold @scrogson is there a discreet list of steps to reproduce this? I'd like to take try getting webpack working, but I'm a total n00b on all the hawtness. Is there or can there be a "how to" in the README?

**Comment by scrogson** [comment]
Hey @maxbeizer this isn't done yet. Once we have something that we're happy with, we'll update the README. Thanks for pinging :smile:
